### ISSUE TITLE
Refactor Media 

### ISSUE THREAD

**Issue by fpigeonjr** [sacodersunited/portillo-tenor#9]
TODO:

- [x] pull in images from Strapi
- [ ] group by role/opera?
- [x] add to a lightbox
- [x] add videos
- [x] add merch
- Use https://github.com/frontend-collective/react-image-lightbox

**Comment by pcast01** [comment]
I have completed everything but now just dealing with the issue of height and padding issue with the video thumbnails.

**Comment by pcast01** [comment]
I have now completed this. All issues are fixed.
